name: '02 - Docker Build and Push'

on:
  workflow_run:
    workflows: ['Semantic Release']
    types:
      - completed
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: false
          tags: node-typescript-template:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
