name: '04 - Deploy to Development'

# 🚀 MANUAL DEPLOYMENT TO DEVELOPMENT
#
# This workflow lets you manually deploy to development environment
#
# HOW TO USE:
# 1. Go to Actions → Deploy to Development → Run workflow
# 2. "Use workflow from" = select which branch's Docker image to deploy (main, v1.0.8, etc.)
# 3. Confirm you want to proceed
# 4. Click Run workflow
#
# REQUIRED SECRETS (set in GitHub Environments → development):
# - CAPROVER_SERVER_DEV: Your development CapRover server URL
# - APP_NAME_DEV: The name of your development CapRover app
# - APP_TOKEN_DEV: The deployment token from your development CapRover app

on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: '⚠️  I understand this will deploy to DEVELOPMENT and confirm I want to proceed'
        required: true
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate deployment inputs
        run: |
          echo "🔍 Validating development deployment inputs..."
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: DEVELOPMENT"
          echo "Confirm deploy: ${{ github.event.inputs.confirm_deploy }}"

          if [ "${{ github.event.inputs.confirm_deploy }}" != "true" ]; then
            echo "❌ Development deployment not confirmed. Exiting."
            exit 1
          fi

          echo "✅ Development deployment inputs validated"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image for deployment
        run: |
          echo "🐳 Pulling Docker image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}"
          docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker images ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Deploy to Development CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: '${{ secrets.CAPROVER_SERVER_DEV }}'
          app: '${{ secrets.APP_NAME_DEV }}'
          token: '${{ secrets.APP_TOKEN_DEV }}'
          image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Development Deployment Summary
        run: |
          echo "🚀 DEVELOPMENT DEPLOYMENT completed successfully!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: DEVELOPMENT"
          echo "Docker image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}"
          echo "Deployed to CapRover app: ${{ secrets.APP_NAME_DEV }}"
          echo "CapRover server: ${{ secrets.CAPROVER_SERVER_DEV }}"
