name: '05 - Deploy to Production'

# 🚀 MANUAL DEPLOYMENT TO PRODUCTION
#
# This workflow lets you manually deploy to production environment
#
# HOW TO USE:
# 1. Go to Actions → Deploy to Production → Run workflow
# 2. "Use workflow from" = select which branch's Docker image to deploy (main, v1.0.8, etc.)
# 3. Confirm you want to proceed
# 4. Click Run workflow
#
# REQUIRED SECRETS:
# - CAPROVER_SERVER_PROD: Your production CapRover server URL
# - APP_NAME_PROD: The name of your production CapRover app
# - APP_TOKEN_PROD: The deployment token from your production CapRover app

on:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: '⚠️  I understand this will deploy to PRODUCTION and confirm I want to proceed'
        required: true
        default: false
        type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate deployment inputs
        run: |
          echo "🔍 Validating production deployment inputs..."
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: PRODUCTION"
          echo "Confirm deploy: ${{ github.event.inputs.confirm_deploy }}"

          if [ "${{ github.event.inputs.confirm_deploy }}" != "true" ]; then
            echo "❌ Production deployment not confirmed. Exiting."
            exit 1
          fi

          echo "✅ Production deployment inputs validated"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image for deployment
        run: |
          echo "🐳 Pulling Docker image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}"
          docker pull ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker images ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Deploy to Production CapRover
        uses: caprover/deploy-from-github@v1.1.2
        with:
          server: '${{ secrets.CAPROVER_SERVER_PROD }}'
          app: '${{ secrets.APP_NAME_PROD }}'
          token: '${{ secrets.APP_TOKEN_PROD }}'
          image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}

      - name: Production Deployment Summary
        run: |
          echo "🚀 PRODUCTION DEPLOYMENT completed successfully!"
          echo "Branch: ${{ github.ref_name }}"
          echo "Environment: PRODUCTION"
          echo "Docker image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}"
          echo "Deployed to CapRover app: ${{ secrets.APP_NAME_PROD }}"
          echo "CapRover server: ${{ secrets.CAPROVER_SERVER_PROD }}"
