name: Deploy

on:
  workflow_run:
    workflows: ['CI/CD Pipeline']
    types:
      - completed
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:run

      - name: Build application
        run: echo "Build step - customize based on your deployment needs"

      - name: Get package version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Deploy to production
        run: |
          echo "Deploying version ${{ steps.package-version.outputs.version }}"
          echo "Deploy step - customize based on your deployment platform"
          # Examples:
          # - For Vercel: npx vercel --prod
          # - For Railway: npx @railway/cli deploy
          # - For Heroku: npx heroku builds:create
          # - For AWS: aws deploy
